package main

import (
	_ "github.com/go-clinic/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server Petstore server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @BasePath /api
func main() {
	config := ReadConfiguration()
	logger := CreateLogger(config)
	router := CreateGinServerInstance(logger)

	RegisterModules(router, config)

	router.Run(config.Server.FullAddress())
}
