basePath: /api
definitions:
  application.AddSpecialitAbilityCommand:
    properties:
      abilityType:
        type: integer
      specialistId:
        type: integer
    type: object
  application.CreatePatientCommand:
    properties:
      firstName:
        type: string
      lastName:
        type: string
    required:
    - firstName
    - lastName
    type: object
  application.CreateSpecialistCommand:
    properties:
      firstName:
        type: string
      lastName:
        type: string
    required:
    - firstName
    - lastName
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /appointments/patients:
    post:
      consumes:
      - application/json
      description: add patient by json
      parameters:
      - description: patient
        in: body
        name: patient
        required: true
        schema:
          $ref: '#/definitions/application.CreatePatientCommand'
      produces:
      - application/json
      responses:
        "201": {}
        "400": {}
        "500": {}
      summary: Create a new patient
      tags:
      - patients
  /appointments/specialists:
    post:
      consumes:
      - application/json
      description: add new specialist by json
      parameters:
      - description: specialist
        in: body
        name: specialist
        required: true
        schema:
          $ref: '#/definitions/application.CreateSpecialistCommand'
      produces:
      - application/json
      responses:
        "201": {}
        "400": {}
        "500": {}
      summary: Create a new specialist
      tags:
      - specialist
  /appointments/specialists/abilities:
    post:
      consumes:
      - application/json
      description: add ability by json
      parameters:
      - description: Specialist Ability
        in: body
        name: specialistAbility
        required: true
        schema:
          $ref: '#/definitions/application.AddSpecialitAbilityCommand'
      produces:
      - application/json
      responses:
        "200": {}
        "400": {}
        "500": {}
      summary: Add ability for given specialist
      tags:
      - specialist
swagger: "2.0"
